### ISSUE TITLE
Transfer to JuliaPackging org?

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaPackaging/ArtifactUtils.jl#21]
Seems like https://github.com/orgs/JuliaPackaging would be a good home for this package. I can add you there if you're not already a member, @simeonschaub.

**Comment by StefanKarpinski** [comment]
Bump... would be great to get this into the packaging org. Let me know if you're willing.

**Comment by simeonschaub** [comment]
Thanks for the bump! Should be done now
